name: Job concurrency

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run:
            sudo apt update && sudo apt install python3 python3-pip -y

      - name: Run the Python script
        run: python Program1.py

  test:
      needs: build
      concurrency:
        group: python-production
        cancel-in-progress: false
      runs-on: ubuntu-latest

      steps:
            - name: Checkout repository
              uses: actions/checkout@v4
      
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
      
            - name: Install Dependencies
              run:
                  sudo apt update && sudo apt install python3 python3-pip -y
      
            - name: Run the Python script
              run: python Program1.py

  deploy:
      needs: test
      runs-on: ubuntu-latest

      steps:
            - name: Checkout repository
              uses: actions/checkout@v4
      
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
      
            - name: Install Dependencies
              run:
                 sudo apt update && sudo apt install python3 python3-pip -y
      
            - name: deploy application
              run: echo "deploying application"
              

    
    
