name: Parallel Job

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run:
            sudo apt install python3 -y
            sudo apt install python3-pip -y

      - name: Run the Python script
        run: python Program1.py

  test:
      runs-on: ubuntu-latest

      steps:
            - name: Checkout repository
              uses: actions/checkout@v4
      
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
      
            - name: Install Dependencies
              run:
                  sudo apt install python3 -y
                  sudo apt install python3-pip -y
      
            - name: Run the Python script
              run: python test_script.py

  deploy:
      runs-on: ubuntu-latest

      steps:
            - name: Checkout repository
              uses: actions/checkout@v4
      
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
      
            - name: Install Dependencies
              run:
                  sudo apt install python3 -y
                  sudo apt install python3-pip -y
      
            - name: deploy application
              run: echo "deploying application"
              

    
    
