name: Script file

on:
  create:
    branches:
      '*'
  pull_request:
      types: opened,closed
  push:
      branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Execute the script file
        run: |
          chmod +x script.sh
          ./script.sh    
