name: Secrets and Variable at Repo level

on: 
  push:

jobs:
  docker-login:
        runs-on: ubuntu-latest
        steps:
          - name: login
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
        
